import json
import io
from typing import TYPE_CHECKING
from models.schemas import AnalysisResult

if TYPE_CHECKING:
    pass


def to_markdown(result: AnalysisResult) -> str:
    """Convert analysis result to Markdown format."""
    lines = [
        "# BoardIQ Analysis Report",
        f"*Generated by BoardIQ · {result.created_at}*",
        "",
    ]

    if result.summary:
        lines += ["## Executive Summary", result.summary, ""]

    if result.language_detected:
        lines += [f"**Languages detected:** {', '.join(result.language_detected)}", ""]

    if result.decisions:
        lines += ["## Decisions Made"]
        lines += [f"- {d}" for d in result.decisions]
        lines.append("")

    if result.risks:
        lines += ["## Risks Identified"]
        lines += [f"- {r}" for r in result.risks]
        lines.append("")

    if result.blockers:
        lines += ["## Blockers"]
        lines += [f"- {b}" for b in result.blockers]
        lines.append("")

    if result.dependencies:
        lines += ["## Dependencies"]
        lines += [f"- {d}" for d in result.dependencies]
        lines.append("")

    if result.tasks:
        lines += ["## Action Items"]
        for task in result.tasks:
            status_emoji = "✅" if task.status == "done" else "🔄" if task.status == "in-progress" else "⬜"
            priority_label = f"[{task.priority.upper()}]" if task.priority else ""
            owner_label = f" — @{task.owner}" if task.owner else ""
            lines.append(f"{status_emoji} **{task.title}** {priority_label}{owner_label}")
        lines.append("")

    if result.flowchart and result.flowchart.mermaid:
        lines += ["## Flowchart / Diagram", "```mermaid", result.flowchart.mermaid, "```", ""]

    if result.contributors:
        lines += ["## Contributors"]
        for c in result.contributors:
            style = f" ({c.handwriting_style})" if c.handwriting_style else ""
            lines.append(f"- **{c.label}**{style}: {', '.join(c.items or [])}")
        lines.append("")

    if result.extracted_text:
        lines += ["## Raw Extracted Text", "```", result.extracted_text, "```", ""]

    return "\n".join(lines)


def to_json(result: AnalysisResult) -> str:
    """Convert analysis result to formatted JSON."""
    return result.model_dump_json(indent=2)


def to_mermaid(result: AnalysisResult) -> str:
    """Extract Mermaid diagram from result."""
    if result.flowchart and result.flowchart.mermaid:
        return result.flowchart.mermaid
    return "graph TD\n    A[No flowchart detected]"
